import { Nunito } from "next/font/google";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "VoucherCodes | Exclusive Vouchers and Codes",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  return (
    <div
      className={`${nunito.className} antialiased bg-gray-100 text-gray-950 selection:bg-teal-100`}
    >
      {children}
    </div>
  );
}
